### ISSUE TITLE
Logging open system call

### ISSUE THREAD

**Issue by bigHosting** [a2o/snoopy#108]
We have the need in our environment to log multiple calls so we started with glibc open system call. Our Chief Software Architect Derek added the open call to snoopy so we want to contribute back to the community with a patch he wrote for snoopy.c version 1.7.10:

int open(const char *path, int oflag, ...)
{
        static int (*func)(const char *, int, ...);
        mode_t mode;

        va_list ap;
        va_start(ap, oflag);
        mode = va_arg(ap, mode_t);
        va_end(ap);

        FN(func,int,"open",(const char *, int, ...));
        if ( (oflag & O_WRONLY) || (oflag & O_RDWR) || (oflag & O_CREAT) )
        {
                char * argv[15];
                int argc = 0;

                if ( oflag & O_RDONLY )   argv[argc++] = "O_RDONLY";
                if ( oflag & O_WRONLY )   argv[argc++] = "O_WRONLY";
                if ( oflag & O_RDWR )     argv[argc++] = "O_RDWR";
                if ( oflag & O_NONBLOCK ) argv[argc++] = "O_NONBLOCK";
                if ( oflag & O_APPEND )   argv[argc++] = "O_APPEND";
                if ( oflag & O_CREAT )    argv[argc++] = "O_CREAT";
                if ( oflag & O_TRUNC )    argv[argc++] = "O_TRUNC";
                if ( oflag & O_EXCL )     argv[argc++] = "O_EXCL";
                if ( oflag & O_NOFOLLOW ) argv[argc++] = "O_NOFOLLOW";
                if ( oflag & O_CLOEXEC )  argv[argc++] = "O_CLOEXEC";
                argv[argc] = NULL;
                snoopy_log(path, argv);
        }
        return (*func) (path, oflag, mode);
}

Thank you

**Comment by bostjan** [comment]
Hello Ms./Mr. X (behind bigHosting username),

Thank you for your contribution, but I will politely reject it, reason below.

### About logging open() syscalls:

I can understand your need for this, but Snoopy's objective is to log executed commands on the system, not general syscall log. ```strace``` command does that just fine. If you need wider tracing, one of the kernel tracing subsystems should do it (ftrace).
If you still feel that Snoopy is the right tool to do so, you can always fork it and release your own version. If you do, I would kindly ask you to rename it, in order to avoid support confusion.


### About general patch/contribution submission:

When writing issues there is this big orange notice that says "Please review the guidelines for contributing to this repository." In there it says contributions are preferred as pull requests (and some additional details).

Additionally, Snoopy version 1.7.0, on which your contribution is based, is no longer supported. We only accept contributions if they are based on current master *great) or latest stable version (also ok, but not optimal).


### Verdict

Therefore, please forward my sincere thanks to you CSA Derek, but I am closing this as "too out of scope".
