### ISSUE TITLE
output to socket

### ISSUE THREAD

**Issue by celevra** [a2o/snoopy#121]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version of Snoopy available @ https://github.com/a2o/snoopy#i1-version-information-and-download-links (not the latest Snoopy version packaged by your favorite distribution, it might be out of date)
- [x] I have read Snoopy documentation @ https://github.com/a2o/snoopy/blob/master/README.md & https://github.com/a2o/snoopy/tree/master/doc
- [x] I have checked FAQ entries @ https://github.com/a2o/snoopy/blob/master/doc/FAQ.md
- [x] I have checked existing Snoopy issues for duplicates and found none @ https://github.com/a2o/snoopy/issues?q=is%3Aissue

## Issue description - Environment basics

(replace 'FILLIN' with actual values from your environment)

| Key                                 | Value             | Comments                         |
| ----------------------------------- | ----------------- | ---------------------------------|
| Architecture:                       | x86_64            | x86 is not supported anymore     |
| Linux distribution:                 | SLES            | |
| Distribution version:               | 11SP4            | |
| Snoopy version:                     | 2.4.6            | |
| Snoopy config file was used:        | yes   | snoopy-install.sh enables this by default |
| Snoopy threading support enabled:   | no   | not enabled by default as of v2.4.4       |

## Issue description - How was Snoopy installed

snoopy-install.sh

## Issue description - Describe the problem you are having
i'm trying to log to a socket, i have set the option:
output = socket:/tmp/echo.sock

i'm running everything as root, no permission issue

## Expected result

output on the server that is creating the socket

## Actual result
nothing

## Steps to reproduce
run this with node.js and set the output option
```
var net = require('net');
var fs = require('fs');

var server = net.createServer(function(con) {
    con.on('data', function(data) {
        if(typeof data != 'undefined' && data != null)
        {
            var str = data.toString();
            var arr = str.split("\n");
            arr.forEach(function(string) {
                 if ( string ) {
                     console.log('Data received by socket: ' + string);
                 }
            })

        }
    });

});

server.listen('/tmp/echo.sock');
```

**Comment by bostjan** [comment]
@celevra The `socket` output came to be because `devlog` logging proved troublesome for systemd-based  systems which pre-create the /dev/log socket and after receiving 10 messages, that socket starts blocking until real message consumer appears (either syslog or journald). This caused boot-time lockups.

That said, I think there is a mismatch in socket types here (note the `unix` socket type):
```
# lsof -p 14484 | grep tmp   # pid 14484 is nodejs process executing your sample socket consumer
nodejs  14484 root   11u  unix 0xffff8807fb7e1a40      0t0 3551346597 /tmp/echo.sock2
```

The error I am seeing is this (`strace snoopy-test-output`):
```
socket(PF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/tmp/echo.sock"}, 16) = -1 EPROTOTYPE (Protocol wrong type for socket)
```

In the code, there is this (in `src/output/socketoutput.c`):
```
    if ((s = socket(AF_LOCAL, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0)) == -1) {
```

There might be three paths forward here:
1. Adjust your socket consumer process to AF_LOCAL and we document this behaviour for future occasions.
2. Update `socket` outout to support multiple socket types.
3. Create a new socket output, including appropriate tests.

Is there an option in NodeJS to try and modify socket type?
