### ISSUE TITLE
Snoopy and systemd journaling

### ISSUE THREAD

**Issue by jimklimov** [a2o/snoopy#200]
We use snoopy in development builds of the product to log whatever shell calls happen, to help troubleshoot why some things happen in the system :) There snoopy is just installed system-wide via `/etc/ld.so.preload:/lib/snoopy.so` and there is no particular `/etc/snoopy.ini` file so far.

Recently there was an effort to constrain the mess in systemd journals by assigning `SyslogIdentifier=%N` to service units of our product components (so it tags logs with the unit name and not executable file name), and I found that while this helped for lines called directly by systemd, the logs emitted by snoopy in the context of that unit are still tagged as 'snoopy' (e.g. when the unit `Exec` implementation calls a method shell script that processes the startup or some other activity). So system-wide logs are still dominated by 'snoopy' lines and it is hard to say from the log entries alone - which parent unit triggered a particular activity.

So, wondering here if some interaction is possible to let snoopy know what name to put in the logs. I suppose it might handle some envvar value as the prefix/suffix (or even complete name?) for the journald/syslog tag (e.g. `snoopy-myunitname`), to avoid any deeper intimacy with systemd in particular?..

Looking at default config file, this seems pretty much like `syslog_ident` at https://github.com/a2o/snoopy/blob/master/etc/snoopy.ini.in#L172 except that the value would be somehow provided by caller so it differs from program to program. And all that in a safe-housed manner as any other user inputs :)

**Comment by bostjan** [comment]
Hey @jimklimov, thanks for explaining the use case.

Although I am (an implicit) systemd user, I am not all that intimately familiar with where unit names can be pulled from. I suspect for systemd-generated messages this is easy, as systemd holds this information in memory (after it reads unit config files). I also suspect that if units are configured in a "systemd way", they emit logs to stdout/stderr, which is in turn captured by systemd, and then again systemd/journald does the tagging with correct syslog identifier before routing the logs wherever they need to go.

What I do not know is this: if a program, even if started by systemd, emits its logs directly into a /dev/log file, does systemd correctly identify these log entries and tags them with the correct unit file?

Anyhow, I think there are two elements at play here:


**1) Snoopy's `ident` setting in the `openlog` call.**

For simplicity, first refer to this (old) syslog output implementation, at line 71:
https://github.com/a2o/snoopy/blob/master/src/output/syslogoutput.c#L71

You can see that syslog's ident string is set there.

Now, according to `openlog` man pages, if you set the value of ident to `NULL`, it apparently uses current program name as identification string:
https://linux.die.net/man/3/openlog

I am not (yet) sure what "null" in this context means, either an argument that is actually null, or a string that immediately terminates with a null byte. You can do the latter right now, by setting `syslog_ident = ""` and try it out, but testing out the former will need Snoopy source code adjustments.

Potentially we can hack something together here, if there is a viable/reliable way to get the information about the unit name from somewhere, be it from the environment, be it from `/proc/PID/cgroup` etc. I _think_ systemd's unit name ends up as a "slice" name in /proc/PID/cgroup, so that could be an option.


**2. Snoopy's chosen log output**

Potentially, you could simply direct Snoopy's output to stdout/stderr and have systemd pick it up and automatically attach the correct syslog ident to it (just unit name, no `snoopy-` prefix).

Although, if you do any interactive debugging in such system/container, you could be in for a potentially floody experience.


**Summary:**

I guess what you're after is something similar to what `message_format` supports right now, and that is:
- Have `syslog_ident` support dynamic formatting
- Have support for `%{systemd_unit_name}` (or something similar) as a formatting option
- Potentially have a new (static or dynamic) option called `syslog_ident_fallback` to fall back to, in case any of the dynamic modifiers used when parsing/constructing the `syslog_ident` fails (i.e. if Snoopy can't find the systemd slice/unit name in /proc/PID/cgroup, fall back to a static `snoopy` ident, or maybe even support the dynamic `%{filename}` or similar).

Would that work?

b.


PS: Patches welcome! :P

**Comment by bostjan** [comment]
@jimklimov, latest git `master` supports using `%{systemd_unit_name}` as a value for `syslog_ident` setting. It should take care of this use case.

PS: It's in a preview state ATM, therefore any real world usage feedback would be appreciated.

**Comment by jimklimov** [comment]
Hi, sorry for falling out of the loop.

I am no longer dealing with that project where snoopy was used for developer-testing "audit", so can't check directly for the use-case. But I'll let them know so maybe they would respond :)

**Comment by bostjan** [comment]
No worries, and thanks for the clarification. :)
