### ISSUE TITLE
Failed to load libsnoopy.so after manual install on Ubuntu 20.04

### ISSUE THREAD

**Issue by vincentroberge** [a2o/snoopy#210]
## Checklist before starting to submit this bug report

I confirm that:
- [X] I am submitting a bug report! :)
- [ X] I have tested this with the [latest stable Snoopy version](https://github.com/a2o/snoopy/releases/latest) (or the latest master build).
- [X ] I have checked the [FAQ](https://github.com/a2o/snoopy/blob/master/doc/FAQ.md).
- [X ] I have read Snoopy's documentation [here](https://github.com/a2o/snoopy/blob/master/README.md) and [here](https://github.com/a2o/snoopy/tree/master/doc).
- [ X] I have searched [Snoopy issues](https://github.com/a2o/snoopy/issues?q=is%3Aissue) for an existing issue that matches my problem, and found none.

## Bug description

I am running Ubuntu 20.04.3

When I do
`$ sudo apt-get install snoopy`
It installs correcntly and it loads, runs and logs when I run applications, including when I run `sudo tcpdump`

When I install snoopy manually using:
```
$ wget -O install-snoopy.sh https://github.com/a2o/snoopy/raw/install/install/install-snoopy.sh &&
chmod 755 install-snoopy.sh &&
sudo ./install-snoopy.sh stable
```

It works for most applications, but for some reasons, it does not work for tcpdump.
When I run
`$ sudo tcpdump`
it prints
`ERROR: ld.so: object '/usr/local/lib/libsnoopy.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.`

I would like to help debug this. The problem may be on my end so I do not want to waste too much of your time. Any help from you would be very much appreciated.

**Comment by bostjan** [comment]
Hey @vincentroberge, looks like [AppArmor](https://wiki.ubuntu.com/AppArmor) is causing this.

The `strace` tool is handy here. Here is a trace of a regular program (`/bin/echo`):
```
# strace /bin/echo asdf
execve("/bin/echo", ["/bin/echo", "asdf"], 0x7ffcf8fdb4a8 /* 23 vars */) = 0
brk(NULL)                               = 0x5638dcf51000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffcf8b5c070) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = 0
openat(AT_FDCWD, "/etc/ld.so.preload", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=28, ...}) = 0
mmap(NULL, 28, PROT_READ|PROT_WRITE, MAP_PRIVATE, 3, 0) = 0x7f15bcc50000
close(3)                                = 0
openat(AT_FDCWD, "/usr/local/lib/libsnoopy.so", O_RDONLY|O_CLOEXEC) = 3
...
```

Trace of `tcpdump` on Ubuntu 20.04 (pay attention to the last line):
```
# strace tcpdump -i eth0 -n not tcp port 22
execve("/usr/sbin/tcpdump", ["tcpdump", "-i", "eth0", "-n", "not", "tcp", "port", "22"], 0x7ffca6a268a8 /* 23 vars */) = 0
brk(NULL)                               = 0x5597ce9f7000
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffdc4e80e40) = -1 EINVAL (Invalid argument)
access("/etc/ld.so.preload", R_OK)      = 0
openat(AT_FDCWD, "/etc/ld.so.preload", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=28, ...}) = 0
mmap(NULL, 28, PROT_READ|PROT_WRITE, MAP_PRIVATE, 3, 0) = 0x7ff2111ed000
close(3)                                = 0
openat(AT_FDCWD, "/usr/local/lib/libsnoopy.so", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
...
```

You can disable AppArmor for `tcpdump` like this:
```
# ln -s /etc/apparmor.d/usr.sbin.tcpdump /etc/apparmor.d/disable/usr.sbin.tcpdump 
# apparmor_parser -R /etc/apparmor.d/disable/usr.sbin.tcpdump

# tcpdump -i eth0 -n not tcp port 22
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
...
```

It looks like the stock Ubuntu Snoopy package (not packaged by me) puts `libsnoopy.so` into another location - `/lib/x86_64-linux-gnu`, whereas the Snoopy installer puts this library into `/usr/local/lib`, a location in-line with where custom files that are not installed by distribution packages should generally end up in.

Changing the target directory to `/lib/x86_64-linux-gnu` resolves the issue (you can do this manually by copying `/usr/local/lib/libsnoopy.*` into that directory and adjust the `/etc/ld.so.preload` content, or install the snoopy manually (either from git or from a package file) and pass the `./configure` command the `--libdir=/lib/x86_64-linux-gnu` argument).

I need to think a bit what should be done here, as I am a bit reluctant to change (complicate) the installer - mainly because it's only a few programs on a specific distribution that are affected here.

**Comment by vincentroberge** [comment]
@bostjan Thank you very much for you comprehensive answer. I now understand the root cause of the problem and the solution is very well explained. I already have experience using the ./configure command to generate custom output without the need for a configuration file. It will be easy to specify the library folder. Thank you again for your rapid and complete answer. Best regards. Vincent

**Comment by bostjan** [comment]
I'll close this issue for now, as it is related to distribution packaging and not core development. For now, distribution packaging is done by other volunteers and their work is not in sync with Snoopy core development.

That said, I am linking this issue to issue #135 - if we ever get to start releasing distribution-specific packages, we'll make sure this issue is addressed then.
