### ISSUE TITLE
Snoopy ignores config under /etc/ (building from source)

### ISSUE THREAD

**Issue by lroehrs** [a2o/snoopy#249]
## Bug description

We updated a few weeks ago to the Version 2.5.0.rc2 because of a bug with jdk.
Since the Update our custom Log pattern wasn't set anymore.
The configuration is set to `/etc/snoopy.ini` as it is described in the docs.

After some rebuild and testing with 2.5.1., I saw that the CLI tool `snoopyctl` using a different config path:
```
root@session1:~# snoopyctl conf
; Options from config file (or defaults): /usr/local/etc/snoopy.ini
...
```

With the copied configuration to `/usr/local/etc/snoopy.ini` it considered again:

```
(message_format = "%{hostname} [uid:%{uid} sid:%{sid} tty:%{tty} cwd:%{cwd} filename:%{filename}]: %{cmdline}")
2022-10-07T15:05:01.331654+02:00 session2 audit[2012731]: session2.lr-test.scalecommerce [uid:0 sid:2012578 tty:/dev/pts/0 cwd:/root filename:/usr/bin/tail]: tail /var/log/audit.log
---
Notice: /Stage[main]/Files/File[/usr/local/lib/libsnoopy.so]/target: target changed '/opt/repos/sc-lib/snoopy/libsnoopy.so' to '/opt/repos/sc-lib/snoopy/libsnoopy.so.2.5.0rc2'
---
2022-10-07T15:06:08.677833+02:00 session2 audit[2013759]: [uid:0 sid:2013729 tty:/dev/pts/0 cwd:/root filename:/usr/bin/tail]: tail /var/log/audit.log
2022-10-07T15:06:21.485180+02:00 session2 audit[2013784]: [uid:0 sid:2013729 tty:/dev/pts/0 cwd:/root filename:/usr/bin/cp]: cp /etc/snoopy.ini /usr/local/etc/snoopy.ini
2022-10-07T15:06:23.342024+02:00 session2 audit[2013785]: session2.lr-test.scalecommerce [uid:0 sid:2013729 tty:/dev/pts/0 cwd:/root filename:/usr/bin/tail]: tail /var/log/audit.log
```

Building on Ubuntu 20.04:
```
  125  2022-10-07 14:00:26 git clone https://github.com/a2o/snoopy snoopy
  126  2022-10-07 14:00:27 cd snoopy
  129  2022-10-07 14:00:38 ./dev-tools/install-dev-software.sh
  130  2022-10-07 14:01:31 ./bootstrap.sh
  132  2022-10-07 14:02:07 ./configure
  133  2022-10-07 14:02:22 make
  141  2022-10-07 14:04:16 make install
```

**Comment by bostjan** [comment]
@lroehrs, I cannot resist to respond with _this is not a bug, it's a feature_ ™ :)

Let me explain:
All projects that use the [GNU Autotools](https://en.wikipedia.org/wiki/GNU_Autotools) in its default configuration have the `install` step place their files under the `/usr/local` directory. This target location can, however, be changed by passing flags to the `./configure` command. In your case, you'll want to add the `--sysconfdir=/etc` flag. You can list all available flags with `./configure --help`. 

You can see the `--sysconfdir` flag being used in [our packaging-related files](https://github.com/a2o/snoopy/blob/master/packaging/deb/rules) or in [our install script](https://github.com/a2o/snoopy/blob/master/install/install-snoopy.sh#L441). It's the standard way of doing things (for projects using Autotools) and you'll see the same pattern in almost* any other software package.

*almost: Some upstream projects may override default target file placements even when using Autotools, but such approach may be frowned upon by the rest of the community, since it generates unexpected results.

**Comment by lroehrs** [comment]
Hi @bostjan, 
thanks for you're fast reply! (And for the project.)

You're right, I totally agree with you. 

I guess we build it a half year ago with the [install-snoopy.sh](https://github.com/a2o/snoopy/blob/master/install/install-snoopy.sh) instead of building it from source. Probably a internal documentation how we build it would be helpful, sorry for wasting you're time. :see_no_evil:

**Comment by bostjan** [comment]
All good, no worries - these Q&A "issues" help others too, when they pop up in google.
