### ISSUE TITLE
Support DESTDIR in etc/Makefile.am

### ISSUE THREAD

**Issue by tkimball83** [a2o/snoopy#31]
When configuring snoopy using --enable-config-file, the Makefile in etc gets executed and snoopy.ini gets installed.  This is great, but unfortunately it doesn't inherit DESTDIR, so you can't build packages that install into a different build root, as it *always* installs into sysconfdir.

For now, I've hacked my RPM spec file like this:

%{__sed} -i -e 's/$(sysconfdir)\/snoopy.ini/$(DESTDIR)$(sysconfdir)\/snoopy.ini/g' etc/Makefile.am

With that said, I'm sure there's a more elegant solution to this.  I'm looking into the fix, but you may know the answer before I get there (assuming my solution is wrong) :)

You can see my latest spec file here:

https://github.com/tkimball83/rpm-specs/blob/master/snoopy.spec

**Comment by bostjan** [comment]
All other files install correctly?

B.

**Comment by tkimball83** [comment]
As far as I can tell, yes.  My RPM includes the following files:

# rpm -ql snoopy
/etc/ld.so.preload
/etc/snoopy.ini
/usr/bin/snoopy-test-output
/usr/lib64/libsnoopy.la
/usr/lib64/libsnoopy.so
/usr/lib64/libsnoopy.so.0
/usr/lib64/libsnoopy.so.0.0.0
/usr/sbin/snoopy-disable
/usr/sbin/snoopy-enable
/usr/share/doc/snoopy-2.2.4
/usr/share/doc/snoopy-2.2.4/COPYING
/usr/share/doc/snoopy-2.2.4/ChangeLog
/usr/share/doc/snoopy-2.2.4/README.md

**Comment by bostjan** [comment]
Ah, yes, snoopy.ini is the only one which has custom installation steps instead of relying on automake's internal methods, in order to not overwrite existing configuration file.

Maybe it would be better if configuration file gets installed every time, but with .new or .x.y.z suffix and we can avoid this custom installation procedure and it's patching.

Thoughts?

b.

PS: If you submit a pull request I will merge it and forget about this in next second :)

**Comment by bostjan** [comment]
Fixed in 2.2.5.
