### ISSUE TITLE
CVE-2014-5009 CVE-2014-5008 CVE-2008-7313 nagios: snoopy: incomplete fixes for command execution flaws

### ISSUE THREAD

**Issue by Eric-Sparks** [a2o/snoopy#74]
Can you tell me if you've addressed these CVEs in your code and if so in which version?  Thanks!

https://bugzilla.redhat.com/show_bug.cgi?id=1121499

**Comment by bostjan** [comment]
Unfortunatelly I was not aware of these CVEs, nor can I access any of their content ATM (restricted access).

CVE-2008-... occured before I took over Snoopy (around 2010), but I think it is related to Snoopy not closing syslog file descriptor (which was opened as fd#3 and this messed with some programs which had numbered FDs hardcoded into them). This was fixed in 1.9.0.

Can you provide contents of mentioned CVEs, or provide me with temporary credentials for accessing them?

b.

**Comment by bostjan** [comment]
Also please make note that I do not do any of the distribution-specific packaging. Those are done by other people, some of them contributed their build files back to Snoopy and this is the reason they are included in the main repository. They are not supported in any way.

If these CVEs are a result of Snoopy package that is outdated, there is very little I can do. Usually, if you provide a bug report (and possibly a fix), I try to release fixed version as soon as possible. But getting new versions into (stable) distributions is sometimes challenging, and I usually leave that to package maintainers (whoever volunteers for that).

This is also the primary reason for creation of Snoopy-recommended way of Snoopy installation - via automated build procedure. This way I can ensure that latest stable version is installed by as much users as possible. This version can then be supported better than if there were multiple versions to support.

b.

**Comment by Eric-Sparks** [comment]
Here's the information regarding the CVEs: https://bugzilla.redhat.com/show_bug.cgi?id=1121497

Looking at the links provided there I don't know if this is still valid or not.  It appears to be affecting several programs.

**Comment by bostjan** [comment]
I believe there is a mixup here. These CVEs are about Snoopy the PHP implementation of HTTP browser: https://sourceforge.net/projects/snoopy/

This is Snoopy the command logging library, also known as Snoopy Logger.

b.

**Comment by Eric-Sparks** [comment]
Opps... too many snoopys!
