### ISSUE TITLE
user manipulation of LD_PRELOAD can prevent snoopy from logging

### ISSUE THREAD

**Issue by jjasen** [a2o/snoopy#88]
# tested on debian jessie
# assuming snoopy 2.x was installed systemwide.

as user:
% wget http://source.a2o.si/download/snoopy/snoopy-latest.tar.gz
% tar -zxf snoopy-latest.tar.gz
% cd snoopy-$VERSION
% ./configure --disable-all-outputs --disable-config-file
# the --disables may not be necessary?
% make
% export LD_PRELOAD=$HOME/snoopy-$VERSION/src/.libs/libsnoopy.so
% bash <--- everything from here on in is NOT logged
% sudo LD_PRELOAD=$HOME/snoopy-$VERSION/src/.libs/libsnoopy.so bash
root@test:# <---- everything here on in is NOT logged

**Comment by bostjan** [comment]
This is by design.

Heh, I mentioned this so many times at various occasions/places, but I never checked whether Snoopy documentation actually contains this piece of information, which now I can see it doesn't.

Here, for example:
http://sourceforge.net/blog/from-slovenia-with-love-a-new-snoopy-logger/

This information deserves to be mentioned on the front page, in README.md. Care to create pull request for this?

tnx,
b.
