### ISSUE TITLE
Snoopy-Install.sh fails for systems not connected to internet.

### ISSUE THREAD

**Issue by PSKyne** [a2o/snoopy#90]
I administer many systems, several of which by design & requirement are NOT connected to the internet and have no way of communicating with the internet. This causes several big issues with installing and/or updating snoopy-logger.

To resolve this issue, I modified the snoopy-installer.sh script to add two new install "modes". 
The first is run by: `snoopy-installer.sh download`. This, when run from an internet-connected system, will download the latest stable snoopy-*.tar.gz file to the same directory from which the script is run.

The second is run by: `snoopy-installer.sh local`. This, when copied to the non-internet-connected machine _with_ the previously downloaded snoopy-*.tar.gz file, will build and install the latest stable snoopy release from the gzipped-tar file.

**Note:** I have ONLY validated the functionality of the script for `download`, `local`, `stable` invocations. I use this new script on my several systems. It takes a lot of frustration and work out of the mix when installing/upgrading snoopy.

Updated script code is submitted to the master branch as: `snoopy-install-NEW.sh`. 
(I'm new to github and this project, so I apologize in advance if I'm submitting this incorrectly.)

**Comment by bostjan** [comment]
Hi again PSK,

let me first state why snoopy-install.sh even exists: there were many requests from fresh Snoopy users, requests which were referring to old, distro-packaged versions of Snoopy. As I have no time to deal with obsolete versions, nor with distro-specific packaging, I created this simple script that makes Snoopy installation experience as smooth as possible - for one specific group of users: first-timers.

The specs for this script were simple:
- user should copy-paste that one command in his console,
- that command/script does everything to set up Snoopy for the user, as best as it can

Eventually it became apparent that, for debugging reasons, "git-master" installation method would simplify testing of bug fixes, if feedback from original reporters was required. Original bug reporters are sometimes regular users who are not that well-versed with package building from git themselves.

Personally I also administer quite a few systems myself (there is a reason I picked up Snoopy maintenance 5 years ago), and all of them have Snoopy installed. But I must stress very firmly: Snoopy repository does not contain my method of (and script for) installation, despite having a very good odds for it (user=maintainer, so there could be a bit of convenience for me).

Then there is another reason: so you administer 2-digit or 3-digit (or even 4-digit) numbere of systems - do you really trust some random script on GitHub to actually do what it says it will do? I, for one, most certainly do not.

Sysadmins that use Snoopy on regular basis, either install it via their preferred method, usually by either building custom packages, or by building it from source, and both methods are automated using some form of configuration management, so there is that.

Now, despite all that was said above, I do value your potential contribution. The "download" and "local" run modes seem sane, but I have the following recommendations:
- the initial part where argument is evaluated (line 32), should not execute the download or anything like that, there are just modes being set. The actual download should be lower
- the "local" command should:
---> check if, and fail gracefully if no snoopy package is found in local directory
---> support passing additional argument of path to snoopy tar.gz file
---> check "ls" for "-v" flag support and use that, or fall back to "-t"
- this is not a requirement for contribution, but if we go forward, there will need to be a bit of refactoring of this script; namely the intial part where operation modes are set, will need to set multiple stages for each operation mode (download yes or no, install dependencies yes or no, proceed with installation yes or no etc). I will do this, do not worry about it, just to let you know that final result might be quite far off from what you have shown now:)

About your git usage:
- do not add new files that are almost identical to existing ones
- this way, I have to manually make diff instead of just looking at github commit page, to see what you have changed and what is untouched
- create pull requests, even if they are rejected in the end. You can always create new pull requests with improved code

I have created a lengthy contributor's guide: https://github.com/a2o/snoopy/blob/master/CONTRIBUTING.md

It is not very Snoopy-specific, but the main thing is: use concise comments - for git commits (you did) **AND for branch names**. For example, when I view Snoopy's git history in "tig" viewer, if I do not see what was merged at the first glance (where only first line of commit message is displayed), then I will not merge it, period. Thus, merging of branch called "patch-1" will never happen. A branch called "feature/add-download-and-local-install-modes" will at least have chances of being merged. Example of good branch-name merges are here:
https://github.com/a2o/snoopy/commit/ce2b0ab25718dc452b6e5899293cd78756b52ba7
https://github.com/a2o/snoopy/commit/d57c0afdd78ddade5a0b66226020a01c62d55cdf
https://github.com/a2o/snoopy/commit/82ba7f8e733990f3a03c7bdfc0f251053f0b5a8c

Now, where to go from here:
- create a new branch with appropriate name
- use your new install file and overwrite existing snoopy-install.sh
- try to fix issues that I have pointed out above
- push to your git repo clone on github
- go to github and click pull request button that will appear, and mind that it is not for patch-1 branch:)

Thanks for taking interest in contributing to Snoopy!
b.

**Comment by bostjan** [comment]
Hi again PSK :)

Do you mind if I merge parts of your code for snoopy-install.sh script?

**Comment by bostjan** [comment]
Initial implmentation is done: ./snoopy-install.sh snoopy-x.y.z.tar.gz.

Download-only mode is pending. I find it quite awkward actually, as if net is not accessible, download mode will not work :)
