### ISSUE TITLE
checking for socat... no

### ISSUE THREAD

**Issue by Packuh** [a2o/snoopy#97]
Hi.
Sorry my eng is bad.
Can you help me?
 
I use HP-UX OS Unix. And I configure Snoopy, but Snoopy ./configure give me error
“checking for socat... no
configure: error: Please install "socat" program. Reason: Needed for "make check" test suite.”
 
Socat doesn't exist in sourse on HP-UX, and I can't establish socat. socat includes functions which aren't supported by HP-UX.
 
Whether it is possible to establish Snoopy without use of socat?
 
Th bay

**Comment by Packuh** [comment]
I gave out to a ./configure a mistake on readlink. .Readlink is absent in HP-UX. I wrote it, the following mistake was with socat

**Comment by bostjan** [comment]
Hi,

I do not think Snoopy will work on HP-UX. It seems HP-UX is missing /etc/ld.so.preload functionality, see here:
http://support.hp.com/us-en/document/c03680658

Of course I am anxiously waiting to be proven wrong on this issue :)
Try Snoopy version 2.3.2 which was the last release that did not require socat program.
Downloads are available here:
http://source.a2o.si/download/snoopy/

It is true that socat is required only for testing suite, so it is not strictly necessary for using Snoopy.

Waiting for your report.
b.

**Comment by Packuh** [comment]
make

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -Wall -Werror -I../../src -g -O2 -c socketoutput.c  -fPIC -DPIC -o .libs/socketoutput.o
socketoutput.c:37:22: error: features.h: No such file or directory
socketoutput.c: In function 'snoopy_output_socketoutput':
socketoutput.c:66: error: 'AF_LOCAL' undeclared (first use in this function)
socketoutput.c:66: error: (Each undeclared identifier is reported only once
socketoutput.c:66: error: for each function it appears in.)
socketoutput.c:66: error: 'SOCK_CLOEXEC' undeclared (first use in this function)
socketoutput.c:66: error: 'SOCK_NONBLOCK' undeclared (first use in this function)
socketoutput.c:85: error: 'MSG_DONTWAIT' undeclared (first use in this function)
socketoutput.c:85: error: 'MSG_NOSIGNAL' undeclared (first use in this function)
*** Error exit code 1

Stop.
*** Error exit code 1

Stop.
*** Error exit code 1

Stop.
*** Error exit code 1

Stop.
*** Error exit code 1

Stop.
*** Error exit code 1

Stop.

**Comment by Packuh** [comment]
the readlink function is realized in gcc. But it isn't present in HP-UX. You want it to bring in a source text? I wrote it on bash, I don't think that it will make for you a problem.

**Comment by bostjan** [comment]
Nasty.

I must admin I really have no access to HP-UX systems to test it myself, nor overwhelming desire to do so :) We might do it with support contract, but not before november.

I will gladly accept patches when provided.

A hint before you start hacking into it:
- devlog output relies on socket output and this is proving will be tricky
- legacy syslog output is your best bet

It should be possible to use it ./configure --enable-output-syslog --with-default-output=syslog --disable-output-devlog --disable-output-socket

This last statement is not supported ATM, because of systemd we needed to stop using syslog() style of message passing and use socket directly.

Honestly, you are so far off of my usual Snoopy comfort zone (Linux, recent versions) that I can not give you more advice ATM :/

b.
